kind: pipeline
type: docker
name: default

steps:
- name: build
  image: node:16.19.0-bullseye
  commands:
  - npm install
  - npm build
  volumes:
  - name: cache
    path: /dist
- name: deploy
  image: httpd:latest
  commands:
    - cp -r dist/ /usr/local/apache2/htdocs/
  volumes:
  - name: cache
    path: /dist

volumes:
  - name: cache
    temp: {}